let products = {
  data: [
    {
      productName: "Paleta color vibes ",
      brand: "Beauty Glazed",
      category: "Sombras",
      price: "60.000",
      state: "Sombras",
      image: "product-0000001.jpg",
    },
    {
      productName: "Paleta color studio ",
      brand: "Beauty Glazed",
      category: "Sombras",
      price: "50.000",
      state: "Sombras",
      image: "product-0000002.jpg",
    },
    {
      productName: "Paleta hawaii",
      brand: "Atenea",
      category: "Sombras",
      price: "78.000",
      state: "Sombras",
      image: "product-0000003.jpg",
    },
    {
      productName: "Paleta majestic",
      brand: "Atenea",
      category: "Sombras",
      price: "70.000",
      state: "Sombras",
      image: "product-0000004.jpg",
    },
    {
      productName: "Paleta sombras birds",
      brand: "Atenea",
      category: "Sombras",
      price: "80.000",
      state: "Sombras",
      image: "product-0000143.jpg",
    },
    {
      productName: "Paleta sombras marvelous",
      brand: "Atenea",
      category: "Sombras",
      price: "70.000",
      state: "Sombras",
      image: "product-0000144.jpg",
    },
    {
      productName: "Paleta art deco",
      brand: "Atenea",
      category: "Sombras",
      price: "37.000",
      state: "Sombras",
      image: "product-0000005.jpg",
    },
    {
      productName: "Paleta perfect mix",
      brand: "Beauty Glazed",
      category: "Sombras",
      price: "35.000",
      state: "Sombras",
      image: "product-0000006.jpg",
    },
    {
      productName: "paleta hono lulu",
      brand: "Atenea",
      category: "Sombras",
      price: "55.000",
      state: "Sombras",
      image: "product-0000007.jpg",
    },
    {
      productName: "paleta Perfect Neutral",
      brand: "Beauty Glazed",
      category: "Sombras",
      price: "29.000",
      state: "Sombras",
      image: "product-0000008.jpg",
    },
    {
      productName: "Paleta Mystic Glow",
      brand: "Ruby Rose",
      category: "Sombras",
      price: "48.000",
      state: "Sombras",
      image: "product-0000009.jpg",
    },
    {
      productName: "Paleta Sublime",
      brand: "Atenea",
      category: "Sombras",
      price: "42.000",
      state: "Sombras",
      image: "product-0000010.jpg",
    },
    {
      productName: "Paleta Atemporal",
      brand: "Atenea",
      category: "Sombras",
      price: "70.000",
      state: "Sombras",
      image: "product-0000011.jpg",
    },
    {
      productName: "Paleta thunder (Tono 6)",
      brand: "Ushas",
      category: "Sombras",
      price: "15.000",
      state: "Sombras",
      image: "product-0000012.jpg",
    },
    {
      productName: "Paleta frutas (Fresa)",
      brand: "Trendy",
      category: "Sombras",
      price: "15.000",
      state: "Sombras",
      image: "product-0000013.jpg",
    },
    {
      productName: "Paleta frutas (uva)",
      brand: "Trendy",
      category: "Sombras",
      price: "15.000",
      state: "Sombras",
      image: "product-0000014.jpg",
    },
    {
      productName: "Paleta frutas (Coco)",
      brand: "Trendy",
      category: "Sombras",
      price: "15.000",
      state: "Sombras",
      image: "product-0000015.jpg",
    },
    {
      productName: "Paleta frutas (Durazno)",
      brand: "Trendy",
      category: "Sombras",
      price: "15.000",
      state: "Sombras",
      image: "product-0000016.jpg",
    },
    {
      productName: "Sombra liquida Sublime (Tono 2)",
      brand: "Atenea",
      category: "Sombras",
      price: "25.000",
      state: "Sombras",
      image: "product-0000017VAR1.jpg",
    },
    {
      productName: "Sombra liquida Sublime (Tono 3)",
      brand: "Atenea",
      category: "Sombras",
      price: "25.000",
      state: "Sombras",
      image: "product-0000017VAR2.jpg",
    },
    {
      productName: "Paleta Blusher",
      brand: "Atenea",
      category: "Rubores",
      price: "30.000",
      state: "Rubores",
      image: "product-0000018.jpg",
    },
    {
      productName: "Paleta Divine Baked",
      brand: "Atenea",
      category: "Iluminadores",
      price: "38.000",
      state: "Iluminadores",
      image: "product-0000019.jpg",
    },
    {
      productName: "Iluminador Baked powder (Tono rosa)",
      brand: "Atenea",
      category: "Iluminadores",
      price: "20.000",
      state: "Iluminadores",
      image: "product-0000020VAR1.jpg",
    },
    {
      productName: "Iluminador Baked powder (Tono bage)",
      brand: "Atenea",
      category: "Iluminadores",
      price: "20.000",
      state: "Iluminadores",
      image: "product-0000020VAR2.jpg",
    },
    {
      productName: "Iluminador corporal (Tono bronce)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "27.000",
      state: "Iluminadores",
      image: "product-0000021VAR1.jpg",
    },
    {
      productName: "Iluminador corporal (Tono plata)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "27.000",
      state: "Iluminadores",
      image: "product-0000021VAR2.jpg",
    },
    {
      productName: "Iluminador corporal (Tono oro rosa)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "27.000",
      state: "Iluminadores",
      image: "product-0000021VAR3.jpg",
    },
    {
      productName: "Iluminador liquido (Tono champaña)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000022VAR1.jpg",
    },
    {
      productName: "Iluminador liquido (Tono dorado)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000022VAR2.jpg",
    },
    {
      productName: "Iluminador liquido (Tono rosa)",
      brand: "Elaya",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000022VAR3.jpg",
    },
    {
      productName: "Paleta iluminadores y contornos girl",
      brand: "Ushas",
      category: "Iluminadores",
      price: "19.000",
      state: "Iluminadores",
      image: "product-0000023.jpg",
    },
    {
      productName: "Paleta cloud",
      brand: "Trendy",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000024.jpg",
    },
    {
      productName: "Iluminador eclipse lunar",
      brand: "Trendy",
      category: "Iluminadores",
      price: "12.000",
      state: "Iluminadores",
      image: "product-0000025.jpg",
    },
    {
      productName: "Polvo de hadas (Tono rosa)",
      brand: "Dolce Bella",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000026VAR1.jpg",
    },
    {
      productName: "Polvo de hadas (Tono cobre)",
      brand: "Dolce Bella",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000026VAR2.jpg",
    },
    {
      productName: "Polvo de hadas (Tono oro)",
      brand: "Dolce Bella",
      category: "Iluminadores",
      price: "15.000",
      state: "Iluminadores",
      image: "product-0000027VAR3.jpg",
    },
    {
      productName: "Brow cocktail cejas",
      brand: "Trendy",
      category: "Sombras",
      price: "18.000",
      state: "Sombras",
      image: "product-0000029.jpg",
    },
    {
      productName: "Rubor en crema love Perfect",
      brand: "Trendy",
      category: "Rubores",
      price: "20.000",
      state: "Rubores",
      image: "product-0000030.jpg",
    },
    {
      productName: "Rubor en barra blush love",
      brand: "Trendy",
      category: "Rubores",
      price: "15.000",
      state: "Rubores",
      image: "product-0000031.jpg",
    },
    {
      productName: "Polvos sueltos (Translucent 01)",
      brand: "Ame",
      category: "Polvos",
      price: "24.500",
      state: "Polvos",
      image: "product-0000032VAR1.jpg",
    },
    {
      productName: "Polvos sueltos (Natural 02)",
      brand: "Ame",
      category: "Polvos",
      price: "24.500",
      state: "Polvos",
      image: "product-0000032VAR2.jpg",
    },
    {
      productName: "Polvos sueltos (Pearl 03)",
      brand: "Ame",
      category: "Polvos",
      price: "24.500",
      state: "Polvos",
      image: "product-0000032VAR3.jpg",
    },
    {
      productName: "Polvos sueltos (Bronce 04)",
      brand: "Ame",
      category: "Polvos",
      price: "24.500",
      state: "Polvos",
      image: "product-0000032VAR4.jpg",
    },
    {
      productName: "Contorno en polvo",
      brand: "Dolce Bella",
      category: "Contornos",
      price: "16.000",
      state: "Contornos",
      image: "product-0000033.jpg",
    },
    {
      productName: "Contorno en barra",
      brand: "Dolce Bella",
      category: "Contornos",
      price: "18.000",
      state: "Contornos",
      image: "product-0000034.jpg",
    },
    {
      productName: "Contorno en barra doble con rubor",
      brand: "Trendy",
      category: "Contornos",
      price: "15.000",
      state: "Contornos",
      image: "product-0000035.jpg",
    },
    {
      productName: "Contorno De Ojos Eye Serum",
      brand: "Trendy",
      category: "Serums",
      price: "12.000",
      state: "Serums",
      image: "product-0000036.jpg",
    },
    {
      productName: "Base tinted (Tono L101-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR1.jpg",
    },
    {
      productName: "Base tinted (Tono L102-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR2.jpg",
    },
    {
      productName: "Base tinted (Tono L103-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR3.jpg",
    },
    {
      productName: "Base tinted (Tono L104-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR4.jpg",
    },
    {
      productName: "Base tinted (Tono L105-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR5.jpg",
    },
    {
      productName: "Base tinted (Tono L106-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR6.jpg",
    },
    {
      productName: "Base tinted (Tono M200-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR7.jpg",
    },
    {
      productName: "Base tinted (Tono M201-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR8.jpg",
    },
    {
      productName: "Base tinted (Tono M202-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR9.jpg",
    },
    {
      productName: "Base tinted (Tono M203-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR10.jpg",
    },
    {
      productName: "Base tinted (Tono M204-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR11.jpg",
    },
    {
      productName: "Base tinted (Tono M205-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR12.jpg",
    },
    {
      productName: "Base tinted (Tono D301-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR13.jpg",
    },
    {
      productName: "Base tinted (Tono D302-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR14.jpg",
    },
    {
      productName: "Base tinted (Tono D303-T)",
      brand: "Ame",
      category: "Bases",
      price: "26.000",
      state: "Bases",
      image: "product-0000037VAR15.jpg",
    },
    {
      productName: "Base larga duracion (Tono 1)",
      brand: "OG",
      category: "Bases",
      price: "30.000",
      state: "Bases",
      image: "product-0000038.jpg",
    },
    {
      productName: "Base BB CREAM (Tono HONEY)",
      brand: "MILS",
      category: "Bases",
      price: "10.000",
      state: "Bases",
      image: "product-0000039.jpg",
    },
    {
      productName: "Base BB CREAM (Tono caramel)",
      brand: "MILS",
      category: "Bases",
      price: "10.000",
      state: "Bases",
      image: "product-0000040.jpg",
    },
    {
      productName: "Corrector ojos alta cobertura",
      brand: "Ruby rose",
      category: "Correctores",
      price: "20.000",
      state: "Correctores",
      image: "product-0000041.jpg",
    },
    {
      productName: "Corrector alto cubrimiento",
      brand: "og",
      category: "Correctores",
      price: "22.000",
      state: "Correctores",
      image: "product-0000042.jpg",
    },
    {
      productName: "Corrector liquido flawless",
      brand: "Ruby rose",
      category: "Correctores",
      price: "13.000",
      state: "Correctores",
      image: "product-0000043.jpg",
    },
    {
      productName: "Corrector liquido concealer",
      brand: "Dolce bella",
      category: "Correctores",
      price: "13.000",
      state: "Correctores",
      image: "product-0000044.jpg",
    },
    {
      productName: "Corrector liquido",
      brand: "Beauty Glazed",
      category: "Correctores",
      price: "12.000",
      state: "Correctores",
      image: "product-0000045.jpg",
    },
    {
      productName: "Corrector mas duracion (Tono 1)",
      brand: "Elaya",
      category: "Correctores",
      price: "11.000",
      state: "Correctores",
      image: "product-0000046VAR1.jpg",
    },
    {
      productName: "Corrector mas duracion (Tono 2)",
      brand: "Elaya",
      category: "Correctores",
      price: "11.000",
      state: "Correctores",
      image: "product-0000046VAR2.jpg",
    },
    {
      productName: "Corrector mas duracion (Tono 3)",
      brand: "Elaya",
      category: "Correctores",
      price: "11.000",
      state: "Correctores",
      image: "product-0000046VAR3.jpg",
    },
    {
      productName: "Corrector mas duracion (Tono 4)",
      brand: "Elaya",
      category: "Correctores",
      price: "11.000",
      state: "Correctores",
      image: "product-0000046VAR4.jpg",
    },
    {
      productName: "Corrector liquido camouflage",
      brand: "Ushas",
      category: "Correctores",
      price: "10.000",
      state: "Correctores",
      image: "product-0000047.jpg",
    },
    {
      productName: "Delineador perfect line 2 en 1",
      brand: "Miis",
      category: "Delineadores",
      price: "15.000",
      state: "Delineadores",
      image: "product-0000048.jpg",
    },
    {
      productName: "Kit delineadores x8 Neon matte rainbow",
      brand: "Trendy",
      category: "Delineadores",
      price: "40.000",
      state: "Delineadores",
      image: "product-0000049.jpg",
    },
    {
      productName: "Delineador doble",
      brand: "Trendy",
      category: "Delineadores",
      price: "15.000",
      state: "Delineadores",
      image: "product-0000050.jpg",
    },
    {
      productName: "Delineador plumon pin up",
      brand: "Trendy",
      category: "Delineadores",
      price: "10.000",
      state: "Delineadores",
      image: "product-0000051.jpg",
    },
    {
      productName: "Delineador plumon super black",
      brand: "Ushas",
      category: "Delineadores",
      price: "12.000",
      state: "Delineadores",
      image: "product-0000052.jpg",
    },
    {
      productName: "lapiz Delineador",
      brand: "dolce bella",
      category: "Delineadores",
      price: "10.000",
      state: "Delineadores",
      image: "product-0000053.jpg",
    },
    {
      productName: "Delineador liquido spring",
      brand: "Ushas",
      category: "Delineadores",
      price: "11.000",
      state: "Delineadores",
      image: "product-0000054.jpg",
    },
    {
      productName: "Delineador glitter (Varios tonos)",
      brand: "Ushas",
      category: "Delineadores",
      price: "10.000",
      state: "Delineadores",
      image: "product-0000055.jpg",
    },
    {
      productName: "Pestañina Collosal 7x Waterproof",
      brand: "Maybeline",
      category: "Pestañinas",
      price: "35.000",
      state: "Pestañinas",
      image: "product-0000056.jpg",
    },
    {
      productName: "Pestañina Collosal 36h",
      brand: "Maybeline",
      category: "Pestañinas",
      price: "37.000",
      state: "Pestañinas",
      image: "product-0000057.jpg",
    },
    {
      productName: "Pestañina False lash Effect",
      brand: "Dolce Bella",
      category: "Pestañinas",
      price: "16.000",
      state: "Pestañinas",
      image: "product-0000058.jpg",
    },
    {
      productName: "Mascara de pestañas boom",
      brand: "Trendy",
      category: "Pestañinas",
      price: "15.000",
      state: "Pestañinas",
      image: "product-0000059.jpg",
    },
    {
      productName: "Mascara de pestañas supreme",
      brand: "Atenea",
      category: "Pestañinas",
      price: "17.000",
      state: "Pestañinas",
      image: "product-0000060.jpg",
    },
    {
      productName: "Mascara de pestañas profesional",
      brand: "Dolce Bella",
      category: "Pestañinas",
      price: "15.000",
      state: "Pestañinas",
      image: "product-0000061.jpg",
    },
    {
      productName: "Mascara de pestañas fortalecedora fresh",
      brand: "Trendy",
      category: "Pestañinas",
      price: "10.000",
      state: "Pestañinas",
      image: "product-0000062.jpg",
    },
    {
      productName: "Gel fijador de cejas",
      brand: "Trendy",
      category: "Cejas",
      price: "15.000",
      state: "Cejas",
      image: "product-0000063.jpg",
    },
    {
      productName: "Serum crecimiento pestañas",
      brand: "Trendy",
      category: "Pestañinas",
      price: "30.000",
      state: "Pestañinas",
      image: "product-0000064.jpg",
    },
    {
      productName: "Jabon de cejas",
      brand: "Trendy",
      category: "Cejas",
      price: "12.000",
      state: "Cejas",
      image: "product-0000065.jpg",
    },
    {
      productName: "Face primer",
      brand: "Dolce Bella",
      category: "Primers",
      price: "30.000",
      state: "Primers",
      image: "product-0000066.jpg",
    },
    {
      productName: "Primer prebase mate",
      brand: "Elaya",
      category: "Primers",
      price: "26.000",
      state: "Primers",
      image: "product-0000067.jpg",
    },
    {
      productName: "Primer serum Summer",
      brand: "Trendy",
      category: "Primers",
      price: "25.000",
      state: "Primers",
      image: "product-0000068.jpg",
    },
    {
      productName: "Primer serum Water melon",
      brand: "Trendy",
      category: "Primers",
      price: "25.000",
      state: "Primers",
      image: "product-0000069.jpg",
    },
    {
      productName: "Spray fijador de maquillaje",
      brand: "Dolce Bella",
      category: "Primers",
      price: "25.000",
      state: "Primers",
      image: "product-0000070.jpg",
    },
    {
      productName: "Spray fijador de maquillaje",
      brand: "Trendy",
      category: "Primers",
      price: "25.000",
      state: "Primers",
      image: "product-0000071.jpg",
    },
    {
      productName: "Aceite desmaquillante",
      brand: "Ame",
      category: "Desmaquillantes",
      price: "18.000",
      state: "Desmaquillantes",
      image: "product-0000072.jpg",
    },
    {
      productName: "Aceite desmaquillante",
      brand: "Trendy",
      category: "Desmaquillantes",
      price: "25.000",
      state: "Desmaquillantes",
      image: "product-0000073.jpg",
    },
    {
      productName: "Espuma desmaquillante de pestañas",
      brand: "Trendy",
      category: "Desmaquillantes",
      price: "25.000",
      state: "Desmaquillantes",
      image: "product-0000074.jpg",
    },
    {
      productName: "Desmaquillador con proteina de leche",
      brand: "Dolce Bella",
      category: "Desmaquillantes",
      price: "14.000",
      state: "Desmaquillantes",
      image: "product-0000075.jpg",
    },
    {
      productName: "Jabon facial limpieza purificante en gel",
      brand: "Ruby Rose",
      category: "Jabones",
      price: "27.000",
      state: "Jabones Faciales",
      image: "product-0000076.jpg",
    },
    {
      productName: "Jabon facial liquido",
      brand: "Dolce Bella",
      category: "Jabones",
      price: "24.000",
      state: "Jabones Faciales",
      image: "product-0000077.jpg",
    },
    {
      productName: "Jabon facial liquido",
      brand: "Trendy",
      category: "Jabones",
      price: "35.000",
      state: "Jabones Faciales",
      image: "product-0000078.jpg",
    },
    {
      productName: "Jabon facial liquido para hombre",
      brand: "Trendy",
      category: "Jabones",
      price: "35.000",
      state: "Jabones Faciales",
      image: "product-0000079.jpg",
    },
    {
      productName: "Serum de vitamina C",
      brand: "Bioaqua",
      category: "Serums",
      price: "28.000",
      state: "Serums",
      image: "product-0000080.jpg",
    },
    {
      productName: "Serum acido hialuronico",
      brand: "Bioaqua",
      category: "Serums",
      price: "25.000",
      state: "Serums",
      image: "product-0000081.jpg",
    },
    {
      productName: "Serum acido hialuronico",
      brand: "Dolce Bella",
      category: "Serums",
      price: "38.000",
      state: "Serums",
      image: "product-0000082.jpg",
    },
    {
      productName: "Suero facial renovador celular",
      brand: "Dolce Bella",
      category: "Serums",
      price: "38.000",
      state: "Serums",
      image: "product-0000083.jpg",
    },
    {
      productName: "Oleo facial anti envejecimiento",
      brand: "Dolce Bella",
      category: "Serums",
      price: "38.000",
      state: "Serums",
      image: "product-0000084.jpg",
    },
    {
      productName: "Suero facial antioxidante",
      brand: "Ruby Rose",
      category: "Serums",
      price: "34.000",
      state: "Serums",
      image: "product-0000085.jpg",
    },
    {
      productName: "Acido hialuronico en crema",
      brand: "Dolce Bella",
      category: "Serums",
      price: "20.000",
      state: "Serums",
      image: "product-0000086.jpg",
    },
    {
      productName: "Suero facial con filtro UV",
      brand: "Dolce Bella",
      category: "Serums",
      price: "22.000",
      state: "Serums",
      image: "product-0000087.jpg",
    },
    {
      productName: "Tonico en spray de aloe vera",
      brand: "Bioaqua",
      category: "Tonicos",
      price: "15.000",
      state: "Tonicos",
      image: "product-0000088.jpg",
    },
    {
      productName: "Tonico rosas y manzanilla (240 ml)",
      brand: "Trendy",
      category: "Tonicos",
      price: "20.000",
      state: "Tonicos",
      image: "product-0000089.jpg",
    },
    {
      productName: "Tonico de rosas (250 ml)",
      brand: "Lula",
      category: "Tonicos",
      price: "20.000",
      state: "Tonicos",
      image: "product-0000090.jpg",
    },
    {
      productName: "Agua micelar pureactive todo en uno (400ml)",
      brand: "Garnier",
      category: "Tonicos",
      price: "30.000",
      state: "Tonicos",
      image: "product-0000091.jpg",
    },
    {
      productName: "Agua micelar todo en uno (400 ml)",
      brand: "Garnier",
      category: "Tonicos",
      price: "30.000",
      state: "Tonicos",
      image: "product-0000092.jpg",
    },
    {
      productName: "Agua micelar (240ml)",
      brand: "Dolce Bella",
      category: "Tonicos",
      price: "18.000",
      state: "Tonicos",
      image: "product-0000093.jpg",
    },
    {
      productName: "Gel hidratante aloe vera",
      brand: "Trendy",
      category: "Hidratantes",
      price: "50.000",
      state: "Hidratantes",
      image: "product-0000094.jpg",
    },
    {
      productName: "Spray hidratante de vitamina c",
      brand: "Bioaqua",
      category: "Hidratantes",
      price: "10.000",
      state: "Hidratantes",
      image: "product-0000095.jpg",
    },
    {
      productName: "Hidratante labios strawberry",
      brand: "Trendy",
      category: "Hidratantes",
      price: "10.000",
      state: "Hidratantes",
      image: "product-0000096.jpg",
    },
    {
      productName: "Mascarilla facial exfoliante",
      brand: "Ruby Rose",
      category: "Mascarillas",
      price: "27.000",
      state: "Mascarillas",
      image: "product-0000097.jpg",
    },
    {
      productName: "Mascarilla en gel exfoliante de arroz",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "22.000",
      state: "Mascarillas",
      image: "product-0000098.jpg",
    },
    {
      productName: "Mascarilla hidrogel de pepino ojos",
      brand: "Trendy",
      category: "Mascarillas",
      price: "20.000",
      state: "Mascarillas",
      image: "product-0000099.jpg",
    },
    {
      productName: "Mascarilla de arcilla",
      brand: "Dolce Bella",
      category: "Mascarillas",
      price: "17.000",
      state: "Mascarillas",
      image: "product-0000100.jpg",
    },
    {
      productName: "Mascarilla carbon activado",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "25.000",
      state: "Mascarillas",
      image: "product-0000101.jpg",
    },
    {
      productName: "Gel aloe vera pink",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "20.000",
      state: "Mascarillas",
      image: "product-0000102.jpg",
    },
    {
      productName: "Mascarilla hidratante aloe vera",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "15.000",
      state: "Mascarillas",
      image: "product-0000103.jpg",
    },
    {
      productName: "Mascarilla exfoliante dual",
      brand: "Dolce Bella",
      category: "Mascarillas",
      price: "25.000",
      state: "Mascarillas",
      image: "product-0000104.jpg",
    },
    {
      productName: "Mascarilla hidratante te verde",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.500",
      state: "Mascarillas",
      image: "product-0000105.jpg",
    },
    {
      productName: "Mascarilla hidratante miel",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.500",
      state: "Mascarillas",
      image: "product-0000106.jpg",
    },
    {
      productName: "Mascarilla hidratante aloe vera",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.500",
      state: "Mascarillas",
      image: "product-0000107.jpg",
    },
    {
      productName: "Mascarilla hidratante pepino",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.500",
      state: "Mascarillas",
      image: "product-0000108.jpg",
    },
    {
      productName: "Mascarilla hidratante esencia de rosa",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.500",
      state: "Mascarillas",
      image: "product-0000109.jpg",
    },
    {
      productName: "Mascarilla hidratante velo hombre",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000110.jpg",
    },
    {
      productName: "Mascarilla acido hialuronico + esencia de centella",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000111.jpg",
    },
    {
      productName: "Mascarilla hidratante de colageno",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000112.jpg",
    },
    {
      productName: "Mascarilla antiacne",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "6.000",
      state: "Mascarillas",
      image: "product-0000113.jpg",
    },
    {
      productName: "Kit parche ojos y labios (Tipo 1)",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000114VAR1.jpg",
    },
    {
      productName: "Kit parche ojos y labios (Tipo 2)",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000114VAR2.jpg",
    },
    {
      productName: "Kit parche ojos y labios (Tipo 3)",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "5.000",
      state: "Mascarillas",
      image: "product-0000114VAR3.jpg",
    },
    {
      productName: "Mascarilla algas marinas ojos",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.000",
      state: "Mascarillas",
      image: "product-0000115.jpg",
    },
    {
      productName: "Mascarilla de nanopeptidos ojos",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.000",
      state: "Mascarillas",
      image: "product-0000116.jpg",
    },
    {
      productName: "Mascarilla colageno oro para ojos",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "3.000",
      state: "Mascarillas",
      image: "product-0000117.jpg",
    },
    {
      productName: "Mascarilla colageno ojos",
      brand: "Trendy",
      category: "Mascarillas",
      price: "3.000",
      state: "Mascarillas",
      image: "product-0000118.jpg",
    },
    {
      productName: "Mascarilla colageno labios",
      brand: "Trendy",
      category: "Mascarillas",
      price: "3.000",
      state: "Mascarillas",
      image: "product-0000119.jpg",
    },
    {
      productName: "Colageno para labios cherry (20 Unidades)",
      brand: "Bioaqua",
      category: "Mascarillas",
      price: "20.000",
      state: "Mascarillas",
      image: "product-0000120.jpg",
    },
    {
      productName: "Mascarilla puntos negros",
      brand: "Trendy",
      category: "Mascarillas",
      price: "4.000",
      state: "Mascarillas",
      image: "product-0000121.jpg",
    },
    {
      productName: "mantequilla corporal",
      brand: "Trendy",
      category: "Cremas",
      price: "25.000",
      state: "Butters & Cremas",
      image: "product-0000122.jpg",
    },
    {
      productName: "Crema hidratante de vitamina C",
      brand: "Bioaqua",
      category: "Cremas",
      price: "22.000",
      state: "Butters & Cremas",
      image: "product-0000123.jpg",
    },
    {
      productName: "Crema antimanchas blanqueadora",
      brand: "Bioaqua",
      category: "Cremas",
      price: "20.000",
      state: "Butters & Cremas",
      image: "product-0000124.jpg",
    },
    {
      productName: "Crema contorno de ojos y arrugas para hombre",
      brand: "Trendy",
      category: "Cremas",
      price: "30.000",
      state: "Butters & Cremas",
      image: "product-0000125.jpg",
    },
    {
      productName: "Beauty blender profesional (Tono rojo)",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000126VAR1.jpg",
    },
    {
      productName: "Beauty blender profesional (Tono purpura)",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000126VAR2.jpg",
    },
    {
      productName: "Beauty blender profesional (Tono rosa)",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000126VAR3.jpg",
    },
    {
      productName: "Limpiador instantaneo de brochas",
      brand: "Lula",
      category: "Accesorios",
      price: "24.000",
      state: "Accesorios",
      image: "product-0000127.jpg",
    },
    {
      productName: "Jabon limpiador de brochas en seco en",
      brand: "Atenea",
      category: "Accesorios",
      price: "28.000",
      state: "Accesorios",
      image: "product-0000128.jpg",
    },
    {
      productName: "Jabon liquido limpiador de brochas",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000129.jpg",
    },
    {
      productName: "Shampoo para brochas",
      brand: "Trendy",
      category: "Accesorios",
      price: "12.000",
      state: "Accesorios",
      image: "product-0000130.jpg",
    },
    {
      productName: "Paleta mezcladora",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000131.jpg",
    },
    {
      productName: "Tapete limpia brochas",
      brand: "Trendy",
      category: "Accesorios",
      price: "10.000",
      state: "Accesorios",
      image: "product-0000132.jpg",
    },
    {
      productName: "Toalla magica desmaquillante",
      brand: "Magic Makeup",
      category: "Accesorios",
      price: "12.000",
      state: "Accesorios",
      image: "product-0000133.jpg",
    },
    {
      productName: "Separador de pestañas",
      brand: "Trendy",
      category: "Accesorios",
      price: "15.000",
      state: "Accesorios",
      image: "product-0000134.jpg",
    },
    {
      productName: "Kit brochas de ojos x12",
      brand: "Trendy",
      category: "Accesorios",
      price: "25.000",
      state: "Accesorios",
      image: "product-0000135.jpg",
    },
    {
      productName: "Kit brochas de ojos x12",
      brand: "Purpure",
      category: "Accesorios",
      price: "18.000",
      state: "Accesorios",
      image: "product-0000136.jpg",
    },
    {
      productName: "Kit brochas de ojos x12 + estuche",
      brand: "Shinee",
      category: "Accesorios",
      price: "30.000",
      state: "Accesorios",
      image: "product-0000137.jpg",
    },
    {
      productName: "Jabon liquido facial trendy + sachet pequeño",
      brand: "Trendy",
      category: "Jabones",
      price: "45.000",
      state: "Jabones Faciales",
      image: "product-0000138.jpg",
    },
    {
      productName: "Sachet tonico de rosas y manzanilla",
      brand: "Trendy",
      category: "Accesorios",
      price: "8.000",
      state: "Accesorios",
      image: "product-0000139.jpg",
    },
    {
      productName: "Sachet grande jabon liquido facial",
      brand: "Trendy",
      category: "Accesorios",
      price: "25.000",
      state: "Accesorios",
      image: "product-0000140.jpg",
    },
    {
      productName: "Sachet pequeño jabon liquido facial",
      brand: "Trendy",
      category: "Accesorios",
      price: "18.000",
      state: "Accesorios",
      image: "product-0000140.jpg",
    },
    {
      productName: "Sachet suero antiedad",
      brand: "Trendy",
      category: "Accesorios",
      price: "25.000",
      state: "Accesorios",
      image: "product-0000142.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 1)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR1.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 2)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR2.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 3)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR3.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 4)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR4.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 5)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR5.jpg",
    },
    {
      productName: "Lip gloss (sweet as s mellon / Tono 6)",
      brand: "Ushas",
      category: "Labiales",
      price: "10.000",
      state: "Labiales",
      image: "product-0000145VAR6.jpg",
    },
  ],
};

for (let i of products.data) {

  let container = document.createElement("div");
  container.classList.add("cards__box", i.category, "hide");

  let container2 = document.createElement("div");
  container2.classList.add("grid__item");

  let container3 = document.createElement("div");
  container3.classList.add("date");
  container2.appendChild(container3);

  let container4 = document.createElement("span");
  container4.classList.add("state__name");
  container4.innerText = i.state.toUpperCase();
  container3.appendChild(container4);

  let container5 = document.createElement("div");
  container5.classList.add("slider");
  container2.appendChild(container5);

  let container6 = document.createElement("div");
  container6.classList.add("slider__item");
  container5.appendChild(container6);

  let image = document.createElement("img");
  image.setAttribute("src", i.image);
  container6.appendChild(image);

  let container7 = document.createElement("div");
  container7.classList.add("meta");
  container2.appendChild(container7);

  let container8 = document.createElement("div");
  container8.classList.add("header__align");
  container7.appendChild(container8);

  let container9 = document.createElement("span");
  container9.classList.add("meta__title");
  container9.innerText = i.productName.toUpperCase();
  container8.appendChild(container9);

  let container10 = document.createElement("span");
  container10.classList.add("meta__brand");
  container10.innerText = i.brand.toUpperCase();
  container8.appendChild(container10);

  let container11 = document.createElement("span");
  container11.classList.add("meta__price");
  container11.innerText = "$" + i.price;
  container7.appendChild(container11);

  container.appendChild(container2);
  document.getElementById("products").appendChild(container)
}

function filterProduct(value) {

  let buttons = document.querySelectorAll(".button-value");

  buttons.forEach((button) => {
    if (value.toUpperCase() == button.innerText.toUpperCase()) {
      button.classList.add("selected__item");
    } else {
      button.classList.remove("selected__item");
    }
  });

  let elements = document.querySelectorAll(".cards__box");

  elements.forEach((element) => {
    if (value == "all") {
      element.classList.remove("hide");
    } else {
      if (element.classList.contains(value)) {
        element.classList.remove("hide");
      } else {
        element.classList.add("hide");
      }
    }
  });
}

document.getElementById("search").addEventListener("click", () => {
  let searchInput = document.getElementById("search-input").value;
  let elements = document.querySelectorAll(".meta__title");
  let element2 = document.querySelectorAll(".meta__brand");
  let containers = document.querySelectorAll(".cards__box");

  elements.forEach((element, index) => {
    if (element.innerText.includes(searchInput.toUpperCase())) {
      containers[index].classList.remove("hide");
    } else {
      containers[index].classList.add("hide");
    }
  });

  element2.forEach((element, index) => {
    if (element.innerText.includes(searchInput.toUpperCase())) {
      containers[index].classList.remove("hide");
    }
  });
});


window.onload = () => {
  filterProduct("all");
};
